// <auto-generated />
namespace EntityCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class RenameKategoriİsimToKategoriAdiInKategorisTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameKategoriİsimToKategoriAdiInKategorisTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202202230809003_RenameKategoriİsimToKategoriAdiInKategorisTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
